site_name: Telegram
theme:
  palette:
    primary: light blue
  logo: ./assets/planejamento/logos/telegram-logo.webp
  favicon: ./assets/planejamento/logos/telegram-logo.webp
  name: material
  features:
    - navigation.tabs
extra_css:
  - stylesheets/styles.css

dev_addr: "0.0.0.0:8000"
